INSERT INTO CUSTOMER(CUSTOMER_ID,NAME,SURNAME,EMAIL,BIRTHDATE) VALUES (CUSTOMER_SEQUENCE_ID.NEXTVAL,'John','Panatsias','ipanatsia@gmail.com','29-OCT-88');
INSERT INTO CUSTOMER(CUSTOMER_ID,NAME,SURNAME,EMAIL,BIRTHDATE) VALUES (CUSTOMER_SEQUENCE_ID.NEXTVAL,'Dimitrios','Panatsias','dpanatsia@gmail.com','29-SEP-51');

INSERT INTO CUSTOMERORDER(ORDER_ID,ORDERNAME,COST,CLIENT_ID) VALUES (ORDER_SEQUENCE_ID.NEXTVAL,'John Panatsias',25,1);
INSERT INTO CUSTOMERORDER(ORDER_ID,ORDERNAME,COST,CLIENT_ID) VALUES (ORDER_SEQUENCE_ID.NEXTVAL,'Dimitrios Panatsias',35,2);

